CBF = ('Bahia','Brusque','CRB','CSA','Chapecoense','Criciúma','Cruzeiro','Guarani','Ituano','Londrina','Novorizontino','Náutico','Operário','Ponte Preta','Sampaio Corrêa','Sport Recife','Tombense','Vasco da Gama','Vila Nova')
print(f'Entre os primeiros 5 times estão: ',end='')
print(f'Lista de times: {CBF}')
print('='*30)
print(f'Os primeiros 5: {CBF[0:5]}')
print('='*30)
print(f'Os últimos 4: {CBF[-4::]}')
print('='*30)
print(f'Times em Ordem Alfabética: {sorted(CBF)}')
print('='*30)
print(f'Posição do Chapecoense é {CBF.index("Chapecoense")+1}')